- name: convert dhcp to static
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-em1
    src: ../templates/template_staticip.j2
  become: yes
  become_user: root

- name: turn off networkmanager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no
  become: yes
  become_user: root

- name: restart network
  systemd:
    name: network
    state: restarted
    enabled: yes
  become: yes
  become_user: root

- name: restart server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  become: yes
  become_user: root
