YUM_LOCAL_REPO:
  ID: localrepo
  NAME: Hotscan Repository
  BASEURL: ftp:///pub
  GPGCHECK: 0
  ISENABLED: 1
  CONFIG:
    PATH: /etc/yum.repos.d/localrepo.repo 
    TEMPLATE: ../templates/template_yum_repo_config.j2
    SRC: ../files
  FTP_FOLDER: /var/ftp/pub
  YUM_UTILS:
    RPM_DEPENDENCY:
      - libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm
      - python-deltarpm-3.6-3.el7.x86_64.rpm
      - deltarpm-3.6-3.el7.x86_64.rpm
      - python-deltarpm-3.6-3.el7.x86_64.rpm
      - createrepo-0.9.9-28.el7.noarch.rpm
  VSFTPD:
    RPM_DEPENDENCY:
      - vsftpd-3.0.2-22.el7.x86_64.rpm 
