IBMMQ:
  WD: /tmp/ibmmq   
  SRC: ../files/WS_MQ_LINUX_ON_X86_64_7.5.0.2_IMG.tar
  BIN: /opt/mqm/bin
  TEMP_FILE_PATH: ~/.channel.in
  RPM_DEPENDENCY:
    - pax
    - rpm-build
  RPM:
    - MQSeriesRuntime-7.5.0-2.x86_64.rpm
    - MQSeriesClient-7.5.0-2.x86_64.rpm
    - MQSeriesSDK-7.5.0-2.x86_64.rpm
    - MQSeriesServer-7.5.0-2.x86_64.rpm
