- hosts: node2
  remote_user: ansible
  connection: ssh
  gather_facts: yes
  vars:
    docker:
      install: true
      insecure: true
      registry: false
      all: false
    network:
      hostname: true
      staticip: true
      all: true
    k8s:
      addnode: false
      node: true
      dashboard: true
      cluster_start: true
    yum:
      config: true
      setup: false
      all: false
  roles:
    - role_yum
    - role_network
    - role_docker
    - role_kubernetes
