- hosts: master
  remote_user: ansible
  connection: ssh
  gather_facts: yes
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/lib/python2.7/site-packages/"
  vars:
    docker:
      install: true
      insecure: true
      registry: false
      all: false
    network:
      hostname: true
      staticip: true
      all: true
    k8s:
      node: true
      master: false
      dashboard: false
      cluster_start: true
    yum:
      config: true
      setup: false
      all: false
  roles:
    - role_yum
    - role_network
    - role_docker
    - role_kubernetes
